=== joseluisillana/EXAMPLE_RAML_PROJECT/MIKE_Raml_v8.0_Project/schemas/methodBodies/structuredLog.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "srv_id": {
      "type": "string"
    },
    "srv_href": {
      "type": "string"
    },
    "srv_type": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "uuaa": {
      "type": "string"
    },
    "inbound_call": {
      "type": "object",
      "properties": {
        "custormer_id": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        },
        "process_type": {
          "type": "string"
        },
        "process_id": {
          "type": "string"
        },
        "session_id": {
          "type": "string"
        },
        "user_action_id": {
          "type": "string"
        },
        "call_id": {
          "type": "string"
        },
        "aap": {
          "type": "string"
        },
        "cms": {
          "type": "object",
          "properties": {
            "channel": {
              "type": "integer"
            },
            "medium": {
              "type": "integer"
            },
            "service": {
              "type": "integer"
            }
          }
        },
        "user_agent": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "instance_name": {
          "type": "string"
        },
        "caller_ip": {
          "type": "string"
        },
        "location": {
          "type": "object",
          "properties": {
            "geolocation": {
              "type": "object",
              "properties": {
                "lat": {
                  "type": "string"
                },
                "lon": {
                  "type": "string"
                }
              }
            },
            "branch": {
              "type": "object",
              "properties": {
                "branch_id": {
                  "type": "string"
                },
                "branch_code": {
                  "type": "string"
                },
                "operative_branch": {
                  "type": "string"
                },
                "bank": {
                  "type": "string"
                },
                "operative_bank": {
                  "type": "string"
                },
                "branch_address": {
                  "type": "object",
                  "properties": {
                    "province": {
                      "type": "integer"
                    },
                    "post_code": {
                      "type": "integer"
                    },
                    "country": {
                      "type": "string"
                    }
                  }
                },
                "region": {
                  "type": "string"
                },
                "head_branch": {
                  "type": "string"
                }
              }
            }
          }
        },
        "health": {
          "type": "object",
          "properties": {
            "timestamp": {
              "type": "integer"
            },
            "response_time": {
              "type": "integer"
            },
            "http_status_code": {
              "type": "integer"
            },
            "response_status": {
              "type": "string"
            },
            "response_code": {
              "type": "string"
            }
          }
        },
        "msg_in": {
          "type": "object",
          "properties": {
            "header": {
              "type": "object",
              "properties": {}
            },
            "body": {
              "type": "object",
              "properties": {}
            }
          }
        },
        "msg_out": {
          "type": "object",
          "properties": {
            "header": {
              "type": "string"
            },
            "body": {
              "type": "string"
            }
          }
        },
        "journal": {
          "type": "string"
        },
        "additional_data": {
          "type": "string"
        }
      }
    },
    "outbound_calls": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "srv_href": {
            "type": "string"
          },
          "srv_type": {
            "type": "string"
          },
          "uuaa": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "srv_id",
    "srv_href",
    "srv_type",
    "uuaa",
    "inbound_call",
    "outbound_calls"
  ]
}

=== joseluisillana/EXAMPLE_RAML_PROJECT/MIKE_Raml_v8.0_Project/examples/methodBodies/structuredLogExample.json
{
  "srv_id": "SMC201500250",
  "srv_href": "http://ei-arqaso.igrupobbva:7050/customers/V01/123/",
  "srv_type": "MSRV (Multichannel Service), NFLW (Nacar Flow), APXTX (APX transaction), MFTX (Host transaction), ROU (Routine)",
  "uuaa": "ENAX, KJIM, QZQP, ATRP...",
  "inbound_call": {
    "custormer_id": "ES0182099817252C",
    "user_id": "xe01379",
    "process_type": "id proceso contratación",
    "process_id": "id instancia única proceso de contratación",
    "session_id": "id Sesión",
    "user_action_id": "id Usuario ejecutor",
    "call_id": "id llamada",
    "aap": "00000037",
    "cms": {
      "channel": 6,
      "medium": 19,
      "service": 105
    },
    "user_agent": "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405",
    "hostname": "spnac008",
    "instance_name": "01(clon)",
    "caller_ip": "192.168.1.123",
    "location": {
      "geolocation": {
        "lat": "37.3591307",
        "lon": "-6.034502"
      },
      "branch": {
        "branch_id": "ES01820437",
        "branch_code": "0437",
        "operative_branch": "0883",
        "bank": "0182",
        "operative_bank": "0001",
        "branch_address": {
          "province": 41,
          "post_code": 28011,
          "country": "País"
        },
        "region": "región",
        "head_branch": " "
      }
    },
    "health": {
      "timestamp": 1444389041012,
      "response_time": 25001,
      "http_status_code": 200,
      "response_status": "OK",
      "response_code": "Servicios: invalidAccountParameter, invalidParameters, etc.Backend: 44725, 66884, etc (o mejor 08, 06, 12, etc.???)"
    },
    "msg_in": {
      "header": {},
      "body": {}
    },
    "msg_out": {
      "header": "{}",
      "body": "{}"
    },
    "journal": "{}",
    "additional_data": "{}"
  },
  "outbound_calls": [
    {
      "srv_href": "http://ei-arqaso.igrupobbva:7050/customers/V01/123/",
      "srv_type": "MSRV (Multichannel Service), NFLW (Nacar Flow), APXTX (APX transaction), MFTX (Host transaction), ROU (Routine)",
      "uuaa": "ENAX, KJIM, QZQP, ATRP..."
    }
  ]
}
